import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>OceanSave</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <Hero heading='Protégeons nos océans' message="OceanSave est une association fictive" />
      <Slider slides={SliderData} />
    </div>
  );
}
